language: node_js
node_js:
  - "10"
cache:
  yarn: true
  directories:
    - node_modules
    - '${NVM_PATH}_modules'
install:
  - yarn
  - cd functions && yarn && cd ..
script:
  - yarn lint
  - echo "Building..."
  - 'if [ "$TRAVIS_BRANCH" == "develop" ]; then yarn build; fi'
  - 'if [ "$TRAVIS_BRANCH" == "master" ]; then yarn build:prod; fi'
before_deploy:
  - echo "Deploying!"
deploy:
  - provider: firebase
    skip_cleanup: true
    'on':
      branch: master
    project: hoverboard-master
    token:
      secure: mGOMoSsbhskl3JOxLA/YkEfWQiCP8iuEVmMrtiHXjYxYnjTWf78tPtmaBsEtTcM6dq/XazQ2InqzyfgmVBaqO96wjgTbpCGQEZcxLHIbsFaCzvo3JT0purfX+e6dKYQOFZDK/sh79nHsRkQmlc2DMnXnWy2JdKrbAd4rWU51nzxmvWLEUHasEezg9cxKY3hfOBVppw1fAcHc/WoGGPF8WWHf69QdutYizy8p3SAOm80IsEYSW8Ih/emElsUUNP3onyWH4HMKK3decnSbhMFD5fhQ98b/b7GDOGaxBxjPyCvHkRuYFvmBBNsO4G68rdxBvfNTaTVUyDsO6mkCJVZjwRrnvWh2iOunA04TNf4nUb/h/qNxgSnQgQCaIO6EWZ1IhIDplmxK42DbBrtZlXrPAw7GDzlE4Grb77DAi/VtD81xdSiXO8nB0AxYG5z+eTMZBBd5LAXLaFw/VgP6O6bHMThHRkJe1XqtPIW0rYOm9XVyUXjj4qQCQObyZUNFvv0w+Mu8qqCo1l1JhIf4Dl/6lbl4NIQk1c1ofatxcWaA9MlPU3PPruhuDapTuCc74003sXiW2nKbt/uKGnc1A9HANCwwGUXGxfCd0ifd1t0T4oQYXW7scsxueBYHhu0PvW8ZeGbu5z5/9UL3hhVPMuuTSrFYngAgssTarSbiPMQXcGo=
  - provider: firebase
    skip_cleanup: true
    'on':
      branch: develop
    project: hoverboard-dev
    token:
      secure: mGOMoSsbhskl3JOxLA/YkEfWQiCP8iuEVmMrtiHXjYxYnjTWf78tPtmaBsEtTcM6dq/XazQ2InqzyfgmVBaqO96wjgTbpCGQEZcxLHIbsFaCzvo3JT0purfX+e6dKYQOFZDK/sh79nHsRkQmlc2DMnXnWy2JdKrbAd4rWU51nzxmvWLEUHasEezg9cxKY3hfOBVppw1fAcHc/WoGGPF8WWHf69QdutYizy8p3SAOm80IsEYSW8Ih/emElsUUNP3onyWH4HMKK3decnSbhMFD5fhQ98b/b7GDOGaxBxjPyCvHkRuYFvmBBNsO4G68rdxBvfNTaTVUyDsO6mkCJVZjwRrnvWh2iOunA04TNf4nUb/h/qNxgSnQgQCaIO6EWZ1IhIDplmxK42DbBrtZlXrPAw7GDzlE4Grb77DAi/VtD81xdSiXO8nB0AxYG5z+eTMZBBd5LAXLaFw/VgP6O6bHMThHRkJe1XqtPIW0rYOm9XVyUXjj4qQCQObyZUNFvv0w+Mu8qqCo1l1JhIf4Dl/6lbl4NIQk1c1ofatxcWaA9MlPU3PPruhuDapTuCc74003sXiW2nKbt/uKGnc1A9HANCwwGUXGxfCd0ifd1t0T4oQYXW7scsxueBYHhu0PvW8ZeGbu5z5/9UL3hhVPMuuTSrFYngAgssTarSbiPMQXcGo=
